# This workflow installs required Python dependencies and then runs the demo.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Demo

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./demo/Titanic

jobs:
  build:

    runs-on: windows-latest  # Deliberately different OS compared to the test run.

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"  # Deliberately different Python version compared to the test run.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # upgrade pip to latest version
        pip install -r requirements.txt      # install pyproject.toml dependencies - excludes optional dependencies (such as visualisation)
    - name: Run basic demo (no repeating scenarios)
      run: |
        python run_demo.py miss
    - name: Run extended demo
      run: |
        python run_demo.py extended
